# 10 -  Mengganti nama kolom pada Data Frame berdasarkan pola

# Import Modules

Modules yang digunakan :

1.pandas as pd

In [1]:
import pandas as pd

print(pd.__version__)

1.1.5

# Persiapan Data Frame

Data Frame yang kita gunakan adalah data set tittanic 

pada awal kita menggunakan fungsi untuk read data csv 

lalu kita membuat data kolom dengan mengisi sejumlah kata kata 

dan sehabis itu kita menggunakan df_backup untuk membackup data yang telah di copy yang parameternya deep dengan nilai True

In [ ]:
df = pd.read_csv('./download/tittanicfull.csv')
df.columns = ['Pclass', 'Survival status', 'full Name', 'sex ', ' Age', 'sib SP', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
df_backup = df.copy

df.head()

# Menggunakan Lowercase untuk nama kolom dan mengganti spasi dengan _

pertama kita memanggil df.columns lalu kita memanggil fungsi string.replace yang akan kita replace yaitu karakter spasi dengan _ 

lalu kita menggunakan fungsi  .str.lower() yang berfungsi mengkonversikan huruf besar menjadi huruf kecil

In [ ]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.head()

# Memangkas Kelebihan Spasi  Pada Nama Kolom

pertama kita harus mengcopy data frame backup dengan parameter deep bernilai True  yang akan ditampung di df

lalu kita akan mengkonversi df.columns dengan lowercase ,setelah itu membuang kelebihan spasi dengan string strip lalu kita akan replace _

In [ ]:
df = df_backup.copy(deep=True)

df.columns = df.columns.str.lower().str.strip().str.replace('  ', '_')
df.head()